### ISSUE TITLE
Protobuf version limited to 3.8 within libxccommon

### ISSUE THREAD

**Issue by XplicitComputing** [XplicitComputing/messages#1] opened 2021-06-28 03:49 UTC
Summary: Google's software engineers have implemented unnecessary constrictive semantics in v3.10+ which disallows us from using bindings in our code gen techniques.

"We are stuck at Protobuf ver-3.8 owed to issues with the code generated by the protoc compiler with newer versions of Protobuf, and our code." - Manfred

"Considering that we don't have to distribute protobuf to customers, as long as we control the dependency stack, there should be no real limitations to end-users. Any 3+ version should be compatible with our distributed runtime." - Graham

**Comment by kwan0xfff** [comment] 2023-09-24 15:38
Protobuf version used by XC build processes has been upgraded to v3.20.3; while builds are successful, we have not tested it yet across an xcserver-xcclient connection. However, this gets around the prior problems we had trying to use Protobuf v3.10+.

This was prompted by experimental builds of xcclient on macOS 12.6.x (Monterey). The software built, but it would crash before bringing up the login panel. At the time of the crash, it was executing code at `google/protobuf/generated_message_util.cc:809`. This is code created by Protobuf software installation. This was repeatable both on x86-64 and Apple Silicon versions of macOS. Before seeking help from Google, it seemed prudent to reproduce the failure in a more recent version of Protobuf. I went with the source code of Protobuf v3.20.1 because it was supported as the current "protobuf@3" on Homebrew (`brew.sh`). Surprisingly, the Protobuf 3v.20.1 code successfully built using the Apple clang 14 toolchain (although the GoogleTests part did not; that part did build successfully with Homebrew llvm@12 clang-12). On the assumption that the installed Protobuf v3.20.x code may be okay (in spite of the GoogleTests build failure), I built and ran xcclient. The login panel came up okay. Thus, the problem encountered with Protobuf v3.8.0 no longer existed.

This success with Protobuf v3.20.x prompted evaluation of it in place of v3.8.0 in the current Ubuntu 20.04 and 22.04 builds. The version has now been updated to v3.20.3, released Sep 29, 2022. https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.3 (v3.8.0 was released on May 24, 2019.) At this writing, the latest version in the v3.x series is v3.24.3, released 2 weeks ago. While v3.20.3 is not the latest version, it certainly deals with latent bugs that may have existed in v3.8.0 and will have fewer compiler-detected depreciation issues going forward.

The remaining task prior to closing this issue is

- [ ] testing xcserver and xcclient built using Protobuf v3.20.3 across a network connection as part of a session with geometry.

**Comment by XplicitComputing** [comment] 2023-10-17 03:11
this is working and can be closed?

**Closed** 2023-10-18 09:25 UTC
Labels: bug

**Comment by kwan0xfff** [comment] 2023-11-21 20:15
As of mid-Nov 2023, we've made extensive use of Messages built using Protobuf v3.20.3 in binaries built by XC-Buildbot. This was not true before Oct 16. However, between Oct 16 and Oct 25, on xplicit-dev-server, we have evidence of 40 client connect/disconnect (i.e., full sessions) to the server. No protocol issues have been reported during that time. (Before Oct 18, when this issue was formally closed, there were only 6 such sessions.)

The initial server version built using the new protocol was 23.1-1003.7e62d2f0-u20 (built on Oct 3). But in viewing server logs on xplicit-dev-server, it was not installed and passed certificate verification until Oct 16. (This is from the xcserver.log* files in /var/opt/xcompute/xcserver/log; there are a few failed certificate verifications before the successful one, but they are not dated.)
